"""
02_preprocessing.py
====================
Stage 2 — Text Cleaning, Front-Matter Removal, Document Statistics

Source: notebook cells 13, 14, 18, 19

Takes the raw_text produced by 01_documents.py and returns a cleaned_text
string ready for chunking in 03_chunking.py.
"""

import re
import numpy as np

from importlib.machinery import SourceFileLoader

# Reuse the loader + PDF_PATH from stage 1
_docs = SourceFileLoader("stage1_documents", "01_documents.py").load_module()


# ==================================================
# PDF / Docling Cleaning
# ==================================================

def clean_document(text):
    """
    Expert cleaning pipeline for Docling output.
    Preserves semantic structure while removing PDF artifacts.
    """

    # 1. Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # 2. Join hyphenated words: nutri-\ntion -> nutrition
    text = re.sub(r'(\w+)-\s*\n\s*(\w+)', r'\1\2', text)

    # 3. Remove HTML comments generated by Docling (<!-- image -->)
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)

    # 4. Remove URLs
    text = re.sub(r'https?://\S+', '', text)

    # 5. Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)

    # 6. Remove download/license notices
    license_patterns = [
        r'Downloaded from.*',
        r'See the Terms and Conditions.*',
        r'OA articles are governed by.*',
    ]

    for p in license_patterns:
        text = re.sub(p, '', text, flags=re.IGNORECASE)

    # 7. Remove repeated page numbers / collapse extra blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = re.sub(r'[ \t]{2,}', ' ', text)

    return text.strip()


# ==================================================
# Remove Front Matter from Book
# ==================================================

def remove_front_matter(text):
    """
    Remove publisher front matter from Docling extracted text.
    Keep the actual book content starting from Introduction.
    """
    start_pattern = r"\nIntroduction\n"

    match = re.search(start_pattern, text, flags=re.IGNORECASE)

    if match:
        text = text[match.start():]

    return text.strip()


# ==================================================
# Document Statistics (per text item, pre-cleaning granularity)
# ==================================================

def compute_document_statistics(text_items):

    word_counts = [
        len(item.split())
        for item in text_items
        if item.strip()
    ]

    return {
        "num_text_items": len(text_items),
        "total_words": int(sum(word_counts)),
        "total_chars": int(sum(len(item) for item in text_items)),
        "avg_words_per_item": round(float(np.mean(word_counts)), 1) if word_counts else 0,
        "median_words_per_item": round(float(np.median(word_counts)), 1) if word_counts else 0,
        "min_words_per_item": int(min(word_counts)) if word_counts else 0,
        "max_words_per_item": int(max(word_counts)) if word_counts else 0,
        "items_low_content": int(sum(1 for wc in word_counts if wc < 20)),
    }


def compare_before_after(raw_items, cleaned_items):

    before_words = sum(len(item.split()) for item in raw_items if item.strip())
    after_words = sum(len(item.split()) for item in cleaned_items if item.strip())

    print("=" * 50)
    print("CLEANING SUMMARY")
    print("=" * 50)
    print(f"Words Before Cleaning : {before_words:,}")
    print(f"Words After Cleaning  : {after_words:,}")
    print(f"Removed Words         : {before_words - after_words:,}")

    if before_words > 0:
        print(f"Retention Rate        : {(after_words / before_words) * 100:.2f}%")


# ==================================================
# Run
# ==================================================

if __name__ == "__main__":

    pdf_document = _docs.load_pdf_document(_docs.PDF_PATH)

    cleaned_text = clean_document(pdf_document["raw_text"])
    cleaned_text = remove_front_matter(cleaned_text)

    print("=" * 60)
    print("AFTER FRONT MATTER REMOVAL")
    print("=" * 60)
    print(cleaned_text[:2000])

    # Save for the next stage
    with open("cleaned_text.txt", "w", encoding="utf-8") as f:
        f.write(cleaned_text)

    print("\nSaved cleaned_text.txt")
