import streamlit as st
import time

# -----------------------------------------------------------------------------
# 1. Page Configuration & Custom CSS
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="NutriRAG | Diabetic Nutrition Search Engine",
    page_icon="🥗",
    layout="wide"
)

# Professional medical/clean theme styling
st.markdown("""
    <style>
    .stApp {
        background-color: #F8FAFC;
    }
    /* Centered Search Hero Header */
    .hero-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E293B;
        text-align: center;
        margin-top: 20px;
    }
    .hero-subtitle {
        font-size: 1.05rem;
        color: #64748B;
        text-align: center;
        margin-bottom: 25px;
    }
    /* Medical Disclaimer Banner */
    .medical-banner {
        background-color: #FEF3C7;
        border-left: 4px solid #F59E0B;
        color: #92400E;
        padding: 10px 16px;
        border-radius: 6px;
        font-size: 0.85rem;
        margin-bottom: 25px;
    }
    /* Source citation cards */
    .source-card {
        background-color: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 8px;
        padding: 12px;
        margin-bottom: 10px;
    }
    </style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 2. Sidebar Settings (Context Parameters)
# -----------------------------------------------------------------------------
with st.sidebar:
    st.header("⚙️ Patient Profile Context")
    st.caption("Customize context injected into your RAG queries.")
    
    diabetes_type = st.selectbox(
        "Diabetes Type",
        ["Type 2 Diabetes", "Type 1 Diabetes", "Prediabetes", "Gestational"]
    )
    
    dietary_pref = st.multiselect(
        "Dietary Restrictions",
        ["Low Sodium", "Vegetarian", "Gluten-Free", "Low GI Focus"],
        default=["Low GI Focus"]
    )
    
    carb_limit = st.slider("Target Carbs per Meal (g)", 15, 75, 45, step=5)
    
    st.divider()
    st.info("💡 **Pro-tip:** Adjusting context automatically updates RAG retrieval parameters for personalized meal safety guidance.")

# -----------------------------------------------------------------------------
# 3. Main Search Interface (Question Entry)
# -----------------------------------------------------------------------------
st.markdown('<div class="hero-title">Diabetic Nutrition Knowledge Engine</div>', unsafe_allow_html=True)
st.markdown('<div class="hero-subtitle">Ask any question regarding food, glycemic index, meal planning, or glucose impact.</div>', unsafe_allow_html=True)

st.markdown(
    '<div class="medical-banner">'
    '<b>⚠️ Disclaimer:</b> Content generated by NutriRAG is grounded in clinical nutrition research but should not replace advice from a certified endocrinologist or Registered Dietitian.'
    '</div>',
    unsafe_allow_html=True
)

# Search Form Container
with st.form(key="rag_search_form", clear_on_submit=False):
    user_question = st.text_input(
        label="Ask your nutritional question:",
        placeholder="e.g., Is oatmeal safe for blood sugar management in Type 2 diabetes?",
        help="Type a complete question to retrieve grounded medical guidelines and food recommendations."
    )
    
    col_submit, col_clear = st.columns([1, 5])
    with col_submit:
        submit_button = st.form_submit_button(label="🔍 Search RAG", use_container_width=True)

# -----------------------------------------------------------------------------
# 4. RAG Backend Integration Placeholder
# -----------------------------------------------------------------------------
def run_diabetic_rag(question: str, context: dict):
    """
    Replace this with your actual RAG retrieval logic (Vector Database + LLM).
    Returns answer text, structured metrics, and reference documents.
    """
    time.sleep(1.0)  # Simulated vector retrieval and response latency
    
    answer_md = f"""
### Key Answer for {context['diabetes_type']}

Yes, **steel-cut or rolled oats** are generally safe and beneficial, provided portion sizes are controlled (**target <= {context['carb_limit']}g carbs**).

* **Glycemic Impact:** Oats contain soluble fiber (**beta-glucan**), which slows glucose absorption and helps prevent post-prandial blood sugar spikes.
* **Best Choice:** Choose steel-cut oats (Low GI ~53) over instant flavored oatmeal (High GI ~75+).
* **Serving Strategy:** Pair oats with healthy fats or proteins—such as chia seeds, almonds, or unsweetened Greek yogurt—to further stabilize blood glucose response.
    """
    
    metrics = {
        "glycemic_index": "Low to Medium (53)",
        "glycemic_load": "Low (~9)",
        "carb_content": "27g per 1/2 cup cooked",
        "fiber_content": "4g"
    }
    
    sources = [
        {
            "title": "American Diabetes Association (ADA) - Carbohydrate Guidelines",
            "url": "https://diabetes.org",
            "excerpt": "Whole grains containing soluble fiber like beta-glucan reduce post-meal glucose spikes and improve insulin sensitivity."
        },
        {
            "title": "Glycemic Index & Diabetes Management (Journal of Clinical Nutrition)",
            "url": "https://ncbi.nlm.nih.gov",
            "excerpt": "Minimally processed oats maintain a low-to-medium GI, whereas instant oats exhibit higher glycemic responses."
        }
    ]
    
    return answer_md, metrics, sources


# -----------------------------------------------------------------------------
# 5. Answer & Results Display Area
# -----------------------------------------------------------------------------
if submit_button and user_question.strip():
    user_context = {
        "diabetes_type": diabetes_type,
        "restrictions": dietary_pref,
        "carb_limit": carb_limit
    }
    
    with st.spinner("Searching medical guidelines & retrieving nutritional data..."):
        answer, metrics, sources = run_diabetic_rag(user_question, user_context)
    
    st.divider()
    
    # Display Answer Section
    col_main, col_stats = st.columns([2, 1])
    
    with col_main:
        st.subheader("💡 RAG Answer")
        st.markdown(answer)
        
        st.subheader("📚 Verified References & Sources")
        for idx, src in enumerate(sources, 1):
            st.markdown(f"""
            <div class="source-card">
                <b>[{idx}] {src['title']}</b><br>
                <small><i>"{src['excerpt']}"</i></small>
            </div>
            """, unsafe_allow_html=True)

    # Display Nutritional Quick Stats Card
    with col_stats:
        st.subheader("📊 Quick Nutritional Profile")
        with st.container(border=True):
            st.metric(label="Est. Glycemic Index", value=metrics["glycemic_index"])
            st.metric(label="Glycemic Load", value=metrics["glycemic_load"])
            st.metric(label="Carbohydrates", value=metrics["carb_content"])
            st.metric(label="Dietary Fiber", value=metrics["fiber_content"])

elif submit_button and not user_question.strip():
    st.warning("Please enter a question before searching.")